name: Angular Test
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 
      - name: Install Dependencies
        run: npm install -f

      - name: Build Angular Application
        run: npm run build

      - name: Commit and Push dist Folder
        run: |
          mkdir -p dist
          git config --global user.email "user@zehntech.com"
          git config --global user.name "zehntech"
          git add .
          git commit -m "latest code"
          git push origin main
